"use client";
import Image from "next/image";
import Link from "next/link";
import {useEffect,useRef} from "react";
import {lockedConcepts} from "./lockedWheelData";
import styles from "./GlassHouseGallery.module.css";

type HouseNode={el:HTMLElement;layer:number};
export default function GlassHouseGallery(){
 const sceneRef=useRef<HTMLDivElement>(null);const nodes=useRef<HouseNode[]>([]);const angle=useRef(0);const velocity=useRef(.000025);const drag=useRef({down:false,x:0,time:0,sample:0});
 useEffect(()=>{nodes.current=Array.from(sceneRef.current?.querySelectorAll<HTMLElement>("[data-house]")||[]).map(el=>({el,layer:-1}));let raf=0;let previous=performance.now();const idle=.000025;const render=(now:number)=>{const dt=Math.min(24,now-previous);previous=now;if(!drag.current.down){if(Math.abs(velocity.current)>idle*1.5)velocity.current*=Math.pow(.972,dt/16.67);else velocity.current+=(idle-velocity.current)*Math.min(1,dt*.0015);angle.current+=velocity.current*dt}const n=nodes.current.length;for(let i=0;i<n;i++){const a=angle.current+i/n*Math.PI*2;const x=Math.sin(a),z=Math.cos(a),depth=(z+1)*.5;const px=x*Math.min(innerWidth*.38,540);const py=Math.sin(a*2+i*.4)*18-depth*10;const scale=.52+depth*.55;const turn=-x*30;const el=nodes.current[i].el;el.style.transform="translate3d("+px.toFixed(2)+"px,"+py.toFixed(2)+"px,"+(z*500).toFixed(2)+"px) scale("+scale.toFixed(4)+") rotateY("+turn.toFixed(2)+"deg)";el.style.opacity=String((.28+depth*.72).toFixed(3));const layer=Math.round(depth*20);if(layer!==nodes.current[i].layer){el.style.zIndex=String(layer);nodes.current[i].layer=layer}}raf=requestAnimationFrame(render)};raf=requestAnimationFrame(render);return()=>cancelAnimationFrame(raf)},[]);
 const onDown=(e:React.PointerEvent<HTMLDivElement>)=>{drag.current={down:true,x:e.clientX,time:performance.now(),sample:0};velocity.current=0;e.currentTarget.setPointerCapture(e.pointerId)};
 const onMove=(e:React.PointerEvent<HTMLDivElement>)=>{if(!drag.current.down)return;const now=performance.now(),dx=e.clientX-drag.current.x,dt=Math.max(5,now-drag.current.time);angle.current+=dx*.0032;const sample=Math.max(-.0025,Math.min(.0025,dx*.0032/dt));drag.current.sample=drag.current.sample*.5+sample*.5;velocity.current=drag.current.sample;drag.current.x=e.clientX;drag.current.time=now};
 const onUp=(e:React.PointerEvent<HTMLDivElement>)=>{drag.current.down=false;velocity.current=drag.current.sample;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId)};
 return <div className={`${styles.page} glass-house-page`}><div className={styles.abyss}/><header className={styles.header}><span>MLR / GLASSHOUSE STUDY</span><h1>Digital worlds.<br/>Built like places.</h1><p>Six complete glass structures orbit through the screen. Drag slowly or flick to send them into the distance.</p></header><div ref={sceneRef} className={styles.scene} role="group" aria-label="Rotating glass house website gallery" onPointerDown={onDown} onPointerMove={onMove} onPointerUp={onUp} onPointerCancel={onUp}><div className={styles.orbitPlane}/>{lockedConcepts.map((item,index)=><article data-house className={styles.house} key={item.slug} style={{"--accent":item.accent} as React.CSSProperties}><div className={styles.structure}><div className={styles.front}><div className={styles.browser}><div className={styles.browserBar}><i/><i/><i/><span>{item.slug.replace(/-/g,"")}.com</span></div><div className={styles.window}><Image src={item.image} alt="" fill sizes="(max-width: 720px) 210px, 360px" quality={90} draggable={false}/><div className={styles.windowShade}/></div></div><div className={styles.label}><small>{item.industry}</small><strong>{item.name}</strong><span>{item.sub}</span></div></div><div className={styles.back}/><div className={styles.left}/><div className={styles.right}/><div className={styles.floor}/><div className={styles.roofA}/><div className={styles.roofB}/><div className={styles.gableFront}/><div className={styles.gableBack}/><i className={styles.beamTL}/><i className={styles.beamTR}/><i className={styles.beamBL}/><i className={styles.beamBR}/><b className={styles.ridge}/></div><span className={styles.number}>0{index+1}</span></article>)}</div><footer className={styles.footer}><span>DRAG SLOW / FLICK FAST</span><Link href="/work">VIEW ALL WORK ↗</Link></footer></div>}
